### ISSUE TITLE
Do not have assigned EIP but seen in the wild...

### ISSUE THREAD

**Issue by stefek99** [PhABC/ethereum-token-standards-list#2]
https://github.com/Giveth/minime

https://github.com/Giveth/yogatoken/blob/master/contracts/YogaToken.sol

https://www.youtube.com/watch?v=peYWgiS2Hmo by @jbaylina

A little bit too busy for PR with the correct formatting :)

**Comment by PhABC** [comment]
Added Yoga and minime, closing this issue. Thanks @stefek99 !
