### ISSUE TITLE
Add related articles to standards

### ISSUE THREAD

**Issue by michielmulders** [PhABC/ethereum-token-standards-list#3]
##  Suggestion
Add related articles to each standard so people can find more relevant information when looking up the standards. I can help with that!

**Comment by PhABC** [comment]
Great idea! Will start adding some. Feel free to post some here or open a PR.

**Comment by michielmulders** [comment]
I've written a couple as well and I'm writing a new one! 
Have some good bookmarks of other explanatory articles.
Is it possible to add me as a contributor to the repository?

In addition, maybe a nice idea to do the same for all proof-of-* consensus protocols?
Can we connect on LinkedIn possibly: https://www.linkedin.com/in/michiel-mulders-013771151/

**Comment by michielmulders** [comment]
@PhABC let me know! :)
You are included in Ethereum Evan Van Ness: http://www.weekinethereum.com/post/175591823558/july-5-2018

**Comment by PhABC** [comment]
@michielmulders 

> "Is it possible to add me as a contributor to the repository?"

Anyone that submits a PR and has that PR merged is considered a "contributor" by github, so just do some PRs and I will merge them asap. 

> "In addition, maybe a nice idea to do the same for all proof-of-* consensus protocols?"

I would personally leave the consensus algorithm list to someone else as this is not directly related to what I'm working on at the moment.
